echo "hello project"
echo "welcome devops team"
echo "hello project"
echo "welcome devops team"
echo "hello quality"
echo "hello testing"
echo "hello there"
echo "hello project"
echo "welcome devops team"
echo "hello project"
echo "welcome devops team"
echo "hello quality"
echo "hello testing"
echo "hello there"
